"""Add pickup details to shipments

Revision ID: f5ed9ed17288
Revises: 
Create Date: 2025-05-18 00:40:24.168340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ed9ed17288'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pickup_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('vehicle_plate', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pickup_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pickup_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_column('pickup_notes')
        batch_op.drop_column('pickup_status')
        batch_op.drop_column('vehicle_plate')
        batch_op.drop_column('pickup_time')
        batch_op.drop_column('pickup_date')

    # ### end Alembic commands ###
